Finish all API auth and test
ColdeGarage/RunRRR-Backend pull request #15
Opened 2017-05-13 09:43 UTC by qmo1222

2017-05-14 09:03 UTC, jwwandy commented on src/clue.js
> +	fire.on('check', function(){
Seems like check is used everytime

2017-05-14 09:06 UTC, jwwandy commented on src/clue.js
> +	fire.on('check', function(){
Why we have so many spaces for identation

2017-05-14 09:09 UTC, jwwandy requested changes

2017-05-14 09:09 UTC, jwwandy commented on src/clue.js
> +	fire.on('check', function(){
Check event might be useless

2017-05-14 09:09 UTC, jwwandy commented on src/clue.js
> +	fire.on('check', function(){
Why we have so many spaces for identation

2017-05-17 08:02 UTC, qmo1222 commented
Pull request so far including :
* Add test for tool image upload
* Add auth level and token
* Modify all tests for auth level and token
* Filter future mission with time for frontend reading
* Fix database timezone problem

2017-05-17 09:44 UTC, qmo1222 commented
Function added :
* Valid area check

2017-05-21 09:39 UTC, jwwandy approved these changes
Great Job!

2017-05-21 09:40 UTC, merged